version: '2'
services:
  background_worker:
    build: .
    command: bundle exec rake background_worker:run
    environment:
      - HOST=${HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=${DATABASE_URL}
      - RACK_ENV=${RACK_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - SENTRY_DSN=${SENTRY_DSN}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - SLACK_NAME=${SLACK_NAME}

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      - HOST=${HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=${DATABASE_URL}
      - RACK_ENV=${RACK_ENV}
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
    ports:
      - "3000:3000"

  logentries:
    command: -t ${LOGENTRIES_TOKEN} --no-stats
    image: logentries/docker-logentries
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
